[package]
name = "basic-messages"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anthropic = { path = "../../anthropic" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
dotenvy = "0.15"
